export type KanaEntry = {
  hiragana: string;
  romaji: string;
  row: string;
};

export const kanaEntries: KanaEntry[] = [
  { hiragana: "あ", romaji: "a", row: "あ行" },
  { hiragana: "い", romaji: "i", row: "あ行" },
  { hiragana: "う", romaji: "u", row: "あ行" },
  { hiragana: "え", romaji: "e", row: "あ行" },
  { hiragana: "お", romaji: "o", row: "あ行" },
  { hiragana: "か", romaji: "ka", row: "か行" },
  { hiragana: "き", romaji: "ki", row: "か行" },
  { hiragana: "く", romaji: "ku", row: "か行" },
  { hiragana: "け", romaji: "ke", row: "か行" },
  { hiragana: "こ", romaji: "ko", row: "か行" },
  { hiragana: "さ", romaji: "sa", row: "さ行" },
  { hiragana: "し", romaji: "shi", row: "さ行" },
  { hiragana: "す", romaji: "su", row: "さ行" },
  { hiragana: "せ", romaji: "se", row: "さ行" },
  { hiragana: "そ", romaji: "so", row: "さ行" },
  { hiragana: "た", romaji: "ta", row: "た行" },
  { hiragana: "ち", romaji: "chi", row: "た行" },
  { hiragana: "つ", romaji: "tsu", row: "た行" },
  { hiragana: "て", romaji: "te", row: "た行" },
  { hiragana: "と", romaji: "to", row: "た行" },
  { hiragana: "な", romaji: "na", row: "な行" },
  { hiragana: "に", romaji: "ni", row: "な行" },
  { hiragana: "ぬ", romaji: "nu", row: "な行" },
  { hiragana: "ね", romaji: "ne", row: "な行" },
  { hiragana: "の", romaji: "no", row: "な行" },
  { hiragana: "は", romaji: "ha", row: "は行" },
  { hiragana: "ひ", romaji: "hi", row: "は行" },
  { hiragana: "ふ", romaji: "fu", row: "は行" },
  { hiragana: "へ", romaji: "he", row: "は行" },
  { hiragana: "ほ", romaji: "ho", row: "は行" },
  { hiragana: "ま", romaji: "ma", row: "ま行" },
  { hiragana: "み", romaji: "mi", row: "ま行" },
  { hiragana: "む", romaji: "mu", row: "ま行" },
  { hiragana: "め", romaji: "me", row: "ま行" },
  { hiragana: "も", romaji: "mo", row: "ま行" },
  { hiragana: "や", romaji: "ya", row: "や行" },
  { hiragana: "ゆ", romaji: "yu", row: "や行" },
  { hiragana: "よ", romaji: "yo", row: "や行" },
  { hiragana: "ら", romaji: "ra", row: "ら行" },
  { hiragana: "り", romaji: "ri", row: "ら行" },
  { hiragana: "る", romaji: "ru", row: "ら行" },
  { hiragana: "れ", romaji: "re", row: "ら行" },
  { hiragana: "ろ", romaji: "ro", row: "ら行" },
  { hiragana: "わ", romaji: "wa", row: "わ行" },
  { hiragana: "を", romaji: "wo", row: "わ行" },
  { hiragana: "ん", romaji: "n", row: "ん" },
];
