export type KanaGroup = "清音" | "浊音" | "半浊音" | "拗音";

export type KanaEntry = {
  hiragana: string;
  romaji: string;
  row: string;
  group: KanaGroup;
  alternatives?: string[];
};

const seion: KanaEntry[] = [
  { hiragana: "あ", romaji: "a", row: "あ行", group: "清音" },
  { hiragana: "い", romaji: "i", row: "あ行", group: "清音" },
  { hiragana: "う", romaji: "u", row: "あ行", group: "清音" },
  { hiragana: "え", romaji: "e", row: "あ行", group: "清音" },
  { hiragana: "お", romaji: "o", row: "あ行", group: "清音" },
  { hiragana: "か", romaji: "ka", row: "か行", group: "清音" },
  { hiragana: "き", romaji: "ki", row: "か行", group: "清音" },
  { hiragana: "く", romaji: "ku", row: "か行", group: "清音" },
  { hiragana: "け", romaji: "ke", row: "か行", group: "清音" },
  { hiragana: "こ", romaji: "ko", row: "か行", group: "清音" },
  { hiragana: "さ", romaji: "sa", row: "さ行", group: "清音" },
  { hiragana: "し", romaji: "shi", row: "さ行", group: "清音", alternatives: ["si"] },
  { hiragana: "す", romaji: "su", row: "さ行", group: "清音" },
  { hiragana: "せ", romaji: "se", row: "さ行", group: "清音" },
  { hiragana: "そ", romaji: "so", row: "さ行", group: "清音" },
  { hiragana: "た", romaji: "ta", row: "た行", group: "清音" },
  { hiragana: "ち", romaji: "chi", row: "た行", group: "清音", alternatives: ["ti"] },
  { hiragana: "つ", romaji: "tsu", row: "た行", group: "清音", alternatives: ["tu"] },
  { hiragana: "て", romaji: "te", row: "た行", group: "清音" },
  { hiragana: "と", romaji: "to", row: "た行", group: "清音" },
  { hiragana: "な", romaji: "na", row: "な行", group: "清音" },
  { hiragana: "に", romaji: "ni", row: "な行", group: "清音" },
  { hiragana: "ぬ", romaji: "nu", row: "な行", group: "清音" },
  { hiragana: "ね", romaji: "ne", row: "な行", group: "清音" },
  { hiragana: "の", romaji: "no", row: "な行", group: "清音" },
  { hiragana: "は", romaji: "ha", row: "は行", group: "清音" },
  { hiragana: "ひ", romaji: "hi", row: "は行", group: "清音" },
  { hiragana: "ふ", romaji: "fu", row: "は行", group: "清音", alternatives: ["hu"] },
  { hiragana: "へ", romaji: "he", row: "は行", group: "清音" },
  { hiragana: "ほ", romaji: "ho", row: "は行", group: "清音" },
  { hiragana: "ま", romaji: "ma", row: "ま行", group: "清音" },
  { hiragana: "み", romaji: "mi", row: "ま行", group: "清音" },
  { hiragana: "む", romaji: "mu", row: "ま行", group: "清音" },
  { hiragana: "め", romaji: "me", row: "ま行", group: "清音" },
  { hiragana: "も", romaji: "mo", row: "ま行", group: "清音" },
  { hiragana: "や", romaji: "ya", row: "や行", group: "清音" },
  { hiragana: "ゆ", romaji: "yu", row: "や行", group: "清音" },
  { hiragana: "よ", romaji: "yo", row: "や行", group: "清音" },
  { hiragana: "ら", romaji: "ra", row: "ら行", group: "清音" },
  { hiragana: "り", romaji: "ri", row: "ら行", group: "清音" },
  { hiragana: "る", romaji: "ru", row: "ら行", group: "清音" },
  { hiragana: "れ", romaji: "re", row: "ら行", group: "清音" },
  { hiragana: "ろ", romaji: "ro", row: "ら行", group: "清音" },
  { hiragana: "わ", romaji: "wa", row: "わ行", group: "清音" },
  { hiragana: "を", romaji: "wo", row: "わ行", group: "清音", alternatives: ["o"] },
  { hiragana: "ん", romaji: "n", row: "ん", group: "清音", alternatives: ["nn", "n'"] },
];

const dakuon: KanaEntry[] = [
  { hiragana: "が", romaji: "ga", row: "が行", group: "浊音" },
  { hiragana: "ぎ", romaji: "gi", row: "が行", group: "浊音" },
  { hiragana: "ぐ", romaji: "gu", row: "が行", group: "浊音" },
  { hiragana: "げ", romaji: "ge", row: "が行", group: "浊音" },
  { hiragana: "ご", romaji: "go", row: "が行", group: "浊音" },
  { hiragana: "ざ", romaji: "za", row: "ざ行", group: "浊音" },
  { hiragana: "じ", romaji: "ji", row: "ざ行", group: "浊音", alternatives: ["zi"] },
  { hiragana: "ず", romaji: "zu", row: "ざ行", group: "浊音" },
  { hiragana: "ぜ", romaji: "ze", row: "ざ行", group: "浊音" },
  { hiragana: "ぞ", romaji: "zo", row: "ざ行", group: "浊音" },
  { hiragana: "だ", romaji: "da", row: "だ行", group: "浊音" },
  { hiragana: "ぢ", romaji: "ji", row: "だ行", group: "浊音", alternatives: ["di", "dji"] },
  { hiragana: "づ", romaji: "zu", row: "だ行", group: "浊音", alternatives: ["du"] },
  { hiragana: "で", romaji: "de", row: "だ行", group: "浊音" },
  { hiragana: "ど", romaji: "do", row: "だ行", group: "浊音" },
  { hiragana: "ば", romaji: "ba", row: "ば行", group: "浊音" },
  { hiragana: "び", romaji: "bi", row: "ば行", group: "浊音" },
  { hiragana: "ぶ", romaji: "bu", row: "ば行", group: "浊音" },
  { hiragana: "べ", romaji: "be", row: "ば行", group: "浊音" },
  { hiragana: "ぼ", romaji: "bo", row: "ば行", group: "浊音" },
];

const handakuon: KanaEntry[] = [
  { hiragana: "ぱ", romaji: "pa", row: "ぱ行", group: "半浊音" },
  { hiragana: "ぴ", romaji: "pi", row: "ぱ行", group: "半浊音" },
  { hiragana: "ぷ", romaji: "pu", row: "ぱ行", group: "半浊音" },
  { hiragana: "ぺ", romaji: "pe", row: "ぱ行", group: "半浊音" },
  { hiragana: "ぽ", romaji: "po", row: "ぱ行", group: "半浊音" },
];

const yoon: KanaEntry[] = [
  { hiragana: "きゃ", romaji: "kya", row: "か行拗音", group: "拗音" },
  { hiragana: "きゅ", romaji: "kyu", row: "か行拗音", group: "拗音" },
  { hiragana: "きょ", romaji: "kyo", row: "か行拗音", group: "拗音" },
  { hiragana: "しゃ", romaji: "sha", row: "さ行拗音", group: "拗音", alternatives: ["sya"] },
  { hiragana: "しゅ", romaji: "shu", row: "さ行拗音", group: "拗音", alternatives: ["syu"] },
  { hiragana: "しょ", romaji: "sho", row: "さ行拗音", group: "拗音", alternatives: ["syo"] },
  { hiragana: "ちゃ", romaji: "cha", row: "た行拗音", group: "拗音", alternatives: ["tya"] },
  { hiragana: "ちゅ", romaji: "chu", row: "た行拗音", group: "拗音", alternatives: ["tyu"] },
  { hiragana: "ちょ", romaji: "cho", row: "た行拗音", group: "拗音", alternatives: ["tyo"] },
  { hiragana: "にゃ", romaji: "nya", row: "な行拗音", group: "拗音" },
  { hiragana: "にゅ", romaji: "nyu", row: "な行拗音", group: "拗音" },
  { hiragana: "にょ", romaji: "nyo", row: "な行拗音", group: "拗音" },
  { hiragana: "ひゃ", romaji: "hya", row: "は行拗音", group: "拗音" },
  { hiragana: "ひゅ", romaji: "hyu", row: "は行拗音", group: "拗音" },
  { hiragana: "ひょ", romaji: "hyo", row: "は行拗音", group: "拗音" },
  { hiragana: "みゃ", romaji: "mya", row: "ま行拗音", group: "拗音" },
  { hiragana: "みゅ", romaji: "myu", row: "ま行拗音", group: "拗音" },
  { hiragana: "みょ", romaji: "myo", row: "ま行拗音", group: "拗音" },
  { hiragana: "りゃ", romaji: "rya", row: "ら行拗音", group: "拗音" },
  { hiragana: "りゅ", romaji: "ryu", row: "ら行拗音", group: "拗音" },
  { hiragana: "りょ", romaji: "ryo", row: "ら行拗音", group: "拗音" },
  { hiragana: "ぎゃ", romaji: "gya", row: "が行拗音", group: "拗音" },
  { hiragana: "ぎゅ", romaji: "gyu", row: "が行拗音", group: "拗音" },
  { hiragana: "ぎょ", romaji: "gyo", row: "が行拗音", group: "拗音" },
  { hiragana: "じゃ", romaji: "ja", row: "ざ行拗音", group: "拗音", alternatives: ["jya", "zya"] },
  { hiragana: "じゅ", romaji: "ju", row: "ざ行拗音", group: "拗音", alternatives: ["jyu", "zyu"] },
  { hiragana: "じょ", romaji: "jo", row: "ざ行拗音", group: "拗音", alternatives: ["jyo", "zyo"] },
  { hiragana: "ぢゃ", romaji: "ja", row: "だ行拗音", group: "拗音", alternatives: ["dya"] },
  { hiragana: "ぢゅ", romaji: "ju", row: "だ行拗音", group: "拗音", alternatives: ["dyu"] },
  { hiragana: "ぢょ", romaji: "jo", row: "だ行拗音", group: "拗音", alternatives: ["dyo"] },
  { hiragana: "びゃ", romaji: "bya", row: "ば行拗音", group: "拗音" },
  { hiragana: "びゅ", romaji: "byu", row: "ば行拗音", group: "拗音" },
  { hiragana: "びょ", romaji: "byo", row: "ば行拗音", group: "拗音" },
  { hiragana: "ぴゃ", romaji: "pya", row: "ぱ行拗音", group: "拗音" },
  { hiragana: "ぴゅ", romaji: "pyu", row: "ぱ行拗音", group: "拗音" },
  { hiragana: "ぴょ", romaji: "pyo", row: "ぱ行拗音", group: "拗音" },
];

export const kanaEntries = [...seion, ...dakuon, ...handakuon, ...yoon];
